library(qqman)
library(QCEWAS)
tiff(res = 300, "Example.tiff",units = "cm",width = 145, height = 35)
man <- read.table("pvalue_decoded.txt", header=T)
head(man)
P_lambda (man$p)
as.data.frame(table(man$CHR))
d <- manhattan(man,chr = 'CHR',bp='Pos',p='p',snp='Marker',col=c("blue","#666666","red"),logp = TRUE,ylab='',xlab='',cex=2.5,cex.lab=1.25,cex.axis=2.6,ylim=c(0.0,17.0),font.axis=2,lwd=2)
dev.off()
